gtv_tele/Controllers/Master/MasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using gtv_tele.DataAccess;

namespace gtv_tele.Controllers.Master
{
    [Authorize]
    public class MasterController : Controller
    {
        AuthenticationDB dbContext = new AuthenticationDB();
        // GET: Master
        [HttpGet]
        public ActionResult ListCustomer()
        {
            ViewBag.DataList = dbContext.Customer;
            return View();
        }

        public ActionResult FormCustomer(int id=0)
        {
            ViewBag.Customer = dbContext.Customer.Find(id);
            ViewBag.Id = id;
            return View();
        }

        [HttpPost]
        public JsonResult SaveCustomer(Customer cust)
        {
            int status = 200; string message = "";
            if(cust.CustomerId == 0)
            {
                try
                {
                    Customer customer = new Customer();
                    customer.CustomerName = cust.CustomerName;
                    customer.CustomerPhone = cust.CustomerPhone;
                    customer.Address = cust.Address;
                    customer.City = cust.City;
                    customer.Region = cust.Region;
                    customer.PostalCode = cust.PostalCode;
                    customer.Country = cust.Country;
                    customer.Created_at = DateTime.Now;
                    customer.Updated_at = DateTime.Now;
                    dbContext.Customer.Add(customer);
                    dbContext.SaveChanges();
                    status = 200; message = "Success Add Customer";
                }catch (Exception ex)
                {
                    status = 400; message = ex.Message;
                }
            }
            else
            {
                try
                {
                    Customer customer = dbContext.Customer.Find(cust.CustomerId);
                    customer.CustomerName = cust.CustomerName;
                    customer.CustomerPhone = cust.CustomerPhone;
                    customer.Address = cust.Address;
                    customer.City = cust.City;
                    customer.Region = cust.Region;
                    customer.PostalCode = cust.PostalCode;
                    customer.Country = cust.Country;                    
                    customer.Updated_at = DateTime.Now;
                    dbContext.SaveChanges();
                    status = 200; message = "Success Change Customer";
                }
                catch (Exception ex)
                {
                    status = 400; message = ex.Message;
                }
            }

            return Json(new { status = status, message = message });
        }

        [HttpGet]
        public JsonResult DeleteCust(int id)
        {
            int status = 200; string message = "";
            
            var cek = dbContext.Project.Where(m => m.CustomerId == id).FirstOrDefault();
            if(cek == null)
            {
                try
                {
                    var cust = dbContext.Customer.Find(id);
                    dbContext.Customer.Remove(cust);
                    dbContext.SaveChanges();
                    status = 200; message = "Success Delete Customer";
                }
                catch(Exception ex)
                {
                    status = 400; message = ex.Message;
                }
            }
            else
            {
                status = 400; message = "Gagal Delete, karena ada beberapa project dan data yang dimiliki";
            }

            return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ListProject()
        {
            ViewBag.DataList = dbContext.Project;
            return View();
        }

        public ActionResult FormProject(int id = 0)
        {
            ViewBag.Project = dbContext.Project.Find(id);
            ViewBag.Customer = dbContext.Customer;
            ViewBag.BodyMessage = dbContext.Body_Message;
            ViewBag.Id = id;
            return View();
        }

        [HttpGet]
        public string BodyMessg(int id)
        {
            string Body = null;

            if(id != 0)
            {
                Body =  dbContext.Body_Message.Find(id).Body;
            }

            return Body == null ? "" : Body;
        }

        [HttpGet]
        public JsonResult DeleteProj(int id)
        {
            int status = 200; string message = "";

            try
            {
                var proj = dbContext.Project.Find(id);
                dbContext.Project.Remove(proj);
                dbContext.SaveChanges();
                status = 200; message = "Success Delete Project";
            }
            catch (Exception ex)
            {
                status = 400; message = ex.Message;
            }

            return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult SaveProject(Project proj)
        {
            int status = 200; string message = "";
            if (proj.ProjectId == 0)
            {
                try
                {
                    Project project = new Project();
                    project.ProjectName = proj.ProjectName;
                    project.ProjectDesc = proj.ProjectDesc;
                    project.CustomerId = proj.CustomerId;
                    project.Body_MessageId = proj.Body_MessageId;
                    project.Created_at = DateTime.Now;
                    project.Updated_at = DateTime.Now;
                    dbContext.Project.Add(project);
                    dbContext.SaveChanges();
                    status = 200; message = "Success Add Project";
                }
                catch (Exception ex)
                {
                    status = 400; message = ex.Message;
                }
            }
            else
            {
                try
                {
                    Project project = dbContext.Project.Find(proj.ProjectId);
                    project.ProjectName = proj.ProjectName;
                    project.ProjectDesc = proj.ProjectDesc;
                    project.CustomerId = proj.CustomerId;
                    project.Body_MessageId = proj.Body_MessageId;                    
                    project.Updated_at = DateTime.Now;
                    dbContext.SaveChanges();
                    status = 200; message = "Success Change Customer";
                }
                catch (Exception ex)
                {
                    status = 400; message = ex.Message;
                }
            }

            return Json(new { status = status, message = message });
        }

        [HttpGet]
        public ActionResult ListSender()
        {
            ViewBag.DataList = dbContext.SettingSender;
            return View();
        }

        [HttpGet]
        public JsonResult DeleteSetSend(int id)
        {
            int status = 200; string message = "";

            try
            {
                var setsend = dbContext.SettingSender.Find(id);
                dbContext.SettingSender.Remove(setsend);
                dbContext.SaveChanges();
                status = 200; message = "Success Delete Project";
            }
            catch (Exception ex)
            {
                status = 400; message = ex.Message;
            }

            return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult FormSetSender(int id = 0)
        {
            ViewBag.SettingSender = dbContext.SettingSender.Find(id);
            ViewBag.Id = id;
            return View();
        }

        public JsonResult SaveSetSender(DataAccess.SettingSender setsend)
        {
            int status = 200; string message = "";
            if (setsend.SettingSenderId == 0)
            {
                try
                {
                    DataAccess.SettingSender setting = new DataAccess.SettingSender();
                    setting.SettingSenderName = setsend.SettingSenderName;
                    setting.Number_Sender = setsend.Number_Sender;
                    setting.ApiId_Sender = setsend.ApiId_Sender;
                    setting.ApiHash_Sender = setsend.ApiHash_Sender;
                    dbContext.SettingSender.Add(setting);
                    dbContext.SaveChanges();
                    status = 200; message = "Success Add Sender";
                }
                catch (Exception ex)
                {
                    status = 400; message = ex.Message;
                }
            }
            else
            {
                try
                {
                    DataAccess.SettingSender setting = dbContext.SettingSender.Find(setsend.SettingSenderId);
                    setting.SettingSenderName = setsend.SettingSenderName;
                    setting.Number_Sender = setsend.Number_Sender;
                    setting.ApiId_Sender = setsend.ApiId_Sender;
                    setting.ApiHash_Sender = setsend.ApiHash_Sender;
                    dbContext.SaveChanges();
                    status = 200; message = "Success Change Sender";
                }
                catch (Exception ex)
                {
                    status = 400; message = ex.Message;
                }
            }

            return Json(new { status = status, message = message });
        }
    }
}

gtv_tele/Views/Master/FormCustomer.cshtml
@model gtv_tele.DataAccess.Customer

@{
    ViewBag.Title = "FormCustomer";
    Layout = "~/Views/Shared/_TemaAdminLTE.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Master
            <small>FormCustomer</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-database"></i> Master</a></li>
            <li class="active"><a href="#">FormCustomer</a></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="col-md-12">
            <div class="row">
                <!-- Horizontal Form -->
                <div class="box box-info">
                    <div class="box-header with-border">

                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">

                        <!-- form start -->
                        @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal", id = "form-customer", name = "form-customer" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="box-body">
                            <input type="hidden" id="CustomerId" name="CustomerId" value="@ViewBag.Id" />

                            <div class="form-group">
                                <label class="col-md-2 col-form-label text-md-right">Nama Customer</label>
                                <div class="col-sm-3">
                                    <input type="text" id="CustomerName" name="CustomerName" class="form-control" value="@if (ViewBag.Customer != null) { @ViewBag.Customer.CustomerName }" placeholder="Customer Name" />
                                </div>

                                <label class="col-md-2 col-form-label text-md-right">Customer Phone</label>
                                <div class="col-sm-3">
                                    <input type="text" id="CustomerPhone" name="CustomerPhone" class="form-control" value="@if (ViewBag.Customer != null) { @ViewBag.Customer.CustomerPhone }" placeholder="Customer Phone" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-2 col-form-label text-md-right">Address</label>
                                <div class="col-sm-3">
                                    <textarea id="Address" name="Address" class="form-control" placeholder="Address">@if (ViewBag.Customer != null) { @ViewBag.Customer.Address }</textarea>
                                </div>

                                <label class="col-md-2 col-form-label text-md-right">City</label>
                                <div class="col-sm-3">
                                    <input type="text" id="City" name="City" class="form-control" value="@if (ViewBag.Customer != null) { @ViewBag.Customer.City }" placeholder="City" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-2 col-form-label text-md-right">Region</label>
                                <div class="col-sm-3">
                                    <input id="Region" name="Region" class="form-control" value="@if (ViewBag.Customer != null) { @ViewBag.Customer.Region }" placeholder="Region" />
                                </div>

                                <label class="col-md-2 col-form-label text-md-right">Postal Code</label>
                                <div class="col-sm-3">
                                    <input type="text" id="PostalCode" name="PostalCode" class="form-control" value="@if (ViewBag.Customer != null) { @ViewBag.Customer.PostalCode }" placeholder="PostalCode" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-2 col-form-label text-md-right">Country</label>
                                <div class="col-sm-3">
                                    <input id="Country" name="Country" class="form-control" value="@if (ViewBag.Customer != null) { @ViewBag.Customer.Country }" placeholder="Country" />
                                </div>
                            </div>

                        </div><!-- /.box-body -->
                            <div class="box-footer">
                                <button type="submit" class="btn btn-success" value="submit" id="submit" name="submit"><span class="fa fa-send"></span> Submit</button>
                            </div><!-- /.box-footer -->

                        }

                    </div>

                    <!-- Loading (remove the following to stop the loading)-->
                    <div class="overlay" id="loading" style="display:none;">
                        <i class="fa fa-refresh fa-spin"></i>
                    </div>
                    <!-- end loading -->

                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>

@section js{
    <script>
       
        $(function () {            
            $('#form-customer').submit(function (e) {
                e.preventDefault();
                var url = "@Url.Action("SaveCustomer", "Master")";
                var formData = new FormData($('#form-customer')[0]);
                //showLoad();

                Swal.fire({
                    title: 'Form Add Customer',
                    text: 'Yakin Mau Lanjut ?',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Ya, Lanjut !',
                    showLoaderOnConfirm: true,
                    preConfirm: (login) => {
                        $.ajax({
                            url: url,
                            type: 'POST',
                            data: formData,
                            contentType: false,
                            processData: false,
                            beforeSend: function () {
                                $('#loading').css('display', 'block');
                            },
                            success: function (response) {
                                //alert(JSON.stringify(response));
                                //hideLoad();
                                if (response.status == 200) {
                                    $('#loading').css('display', 'none');
                                    Swal.fire({
                                        icon: 'success',
                                        title: response.message,
                                        onClose: () => {
                                            $('#form-customer')[0].reset();
                                        }
                                    });
                                } else {
                                    if (response.status == 400) {
                                        $('#loading').css('display', 'none');
                                        Swal.fire({
                                            icon: 'error',
                                            title: response.message,
                                            onClose: () => {
                                                $('#form-customer')[0].reset();
                                            }
                                        });
                                    }
                                }
                            },
                            error: function (response) {
                                //hideLoad();
                                $('#loading').css('display', 'none');
                                Swal.fire({
                                    icon: 'error',
                                    title: 'Error',
                                    onClose: () => {
                                        $('#form-customer')[0].reset();
                                    }
                                });
                            }
                        });
                    }
                });
            });
        });
    </script>
}

gtv_tele/Views/Master/FormProject.cshtml
@{
    ViewBag.Title = "FormProject";
    Layout = "~/Views/Shared/_TemaAdminLTE.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Master
            <small>FormProject</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-database"></i> Master</a></li>
            <li class="active"><a href="#">FormProject</a></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="col-md-12">
            <div class="row">
                <!-- Horizontal Form -->
                <div class="box box-info">
                    <div class="box-header with-border">

                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">

                        <!-- form start -->
                        @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal", id = "form-project", name = "form-project" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="box-body">
                                <input type="hidden" id="ProjectId" name="ProjectId" value="@ViewBag.Id" />

                                <div class="form-group">
                                    <label class="col-md-2 col-form-label text-md-right">Customer Name</label>
                                    <div class="col-sm-3">
                                        <select class="form-control select2" id="CustomerId" name="CustomerId">
                                            <option value="0">Pilih</option>
                                            @foreach (var cust in ViewBag.Customer)
                                            {
                                                <option value="@cust.CustomerId" @if (ViewBag.Project != null) { if (cust.CustomerId == ViewBag.Project.CustomerId) { <text>
                                                        selected
                                                        </text>  } }>
                                                    @cust.CustomerName
                                                </option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="col-md-2 col-form-label text-md-right">Project Name</label>
                                    <div class="col-sm-3">
                                        <input type="text" id="ProjectName" name="ProjectName" class="form-control" value="@if (ViewBag.Project != null) { @ViewBag.Project.ProjectName }" placeholder="Project Name" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-2 col-form-label text-md-right">Project Desc</label>
                                    <div class="col-sm-3">
                                        <input type="text" id="ProjectDesc" name="ProjectDesc" class="form-control" value="@if (ViewBag.Project != null) { @ViewBag.Project.ProjectDesc }" placeholder="Project Desc" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-2 col-form-label text-md-right">Body Message</label>
                                    <div class="col-sm-3">
                                        <select class="form-control select2" id="Body_MessageId" name="Body_MessageId" onchange="SetBody()">
                                            <option value="0">Pilih</option>
                                            @foreach (var bm in ViewBag.BodyMessage)
                                            {
                                                <option value="@bm.Body_MessageId" @if (ViewBag.Project != null) { if (bm.Body_MessageId == ViewBag.Project.Body_MessageId) { <text>
                                                        selected
                                                        </text> } }>
                                                    @bm.Nama_Body
                                                </option>
                                            }
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-2 col-form-label text-md-right"></label>
                                    <div class="col-sm-3">
                                        <p id="bodymess">

                                        </p>
                                    </div>
                                </div>

                            </div><!-- /.box-body -->
                            <div class="box-footer">
                                <button type="submit" class="btn btn-success" value="submit" id="submit" name="submit"><span class="fa fa-send"></span> Submit</button>
                            </div><!-- /.box-footer -->

                        }

                    </div>

                    <!-- Loading (remove the following to stop the loading)-->
                    <div class="overlay" id="loading" style="display:none;">
                        <i class="fa fa-refresh fa-spin"></i>
                    </div>
                    <!-- end loading -->

                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>

@section js{
    <script>

        SetBody();
        function SetBody() {
            var id = $("#Body_MessageId").val();
            $.get("@Url.Action("BodyMessg","Master")", { id: id }, function (data, status) {
                $("#bodymess").text(data);
            });
        }

        $(function () {

            $(".select2").select2();

            $('#form-project').submit(function (e) {
                e.preventDefault();
                var url = "@Url.Action("SaveProject", "Master")";
                var formData = new FormData($('#form-project')[0]);
                //showLoad();

                Swal.fire({
                    title: 'Form Add Project',
                    text: 'Yakin Mau Lanjut ?',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Ya, Lanjut !',
                    showLoaderOnConfirm: true,
                    preConfirm: (login) => {
                        $.ajax({
                            url: url,
                            type: 'POST',
                            data: formData,
                            contentType: false,
                            processData: false,
                            beforeSend: function () {
                                $('#loading').css('display', 'block');
                            },
                            success: function (response) {
                                //alert(JSON.stringify(response));
                                //hideLoad();
                                if (response.status == 200) {
                                    $('#loading').css('display', 'none');
                                    Swal.fire({
                                        icon: 'success',
                                        title: response.message,
                                        onClose: () => {
                                            $('#form-project')[0].reset();
                                        }
                                    });
                                } else {
                                    if (response.status == 400) {
                                        $('#loading').css('display', 'none');
                                        Swal.fire({
                                            icon: 'error',
                                            title: response.message,
                                            onClose: () => {
                                                $('#form-project')[0].reset();
                                            }
                                        });
                                    }
                                }
                            },
                            error: function (response) {
                                //hideLoad();
                                $('#loading').css('display', 'none');
                                Swal.fire({
                                    icon: 'error',
                                    title: 'Error',
                                    onClose: () => {
                                        $('#form-project')[0].reset();
                                    }
                                });
                            }
                        });
                    }
                });
            });
        });
    </script>
}