gtv_tele/Controllers/SettingSender/SettingController.cs
using gtv_tele.Functions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using gtv_tele.DataAccess;
using gtv_tele.Functions;
using static System.Windows.Forms.VisualStyles.VisualStyleElement;

namespace gtv_tele.Controllers.SettingSender
{
    [Authorize]
    public class SettingController : Controller
    {
        AuthenticationDB dbContext = new AuthenticationDB();
        // GET: Setting
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.DataList = dbContext.VariableToBody;
            return View();
        }

        [HttpGet]
        public ActionResult FormVarToField(int id=0)
        {
            ViewBag.VariableToBodyName = dbContext.VariableToBody.Where(m => m.VariableToBodyId == id).FirstOrDefault();
            ViewBag.DataList = dbContext.VariableToBodyDetail.Where(m => m.VariableToBodyId == id);


            ViewBag.FieldName = General.GetMembers(typeof(Master_Upload_Detail));
            ViewBag.Id = id;    
            return View();
        }

        [HttpPost]
        public JsonResult SaveData(List<string> VariableName =null, List<string> VariableField=null)
        {
            long id = Int64.Parse(Request["id"]);
            string nama = Request["VariableToBodyName"];
            string message = ""; int status = 200;
            if(id == 0)
            {                
                try
                {
                    VariableToBody vtb = new VariableToBody();
                    vtb.VariableToBodyName = nama;
                    dbContext.VariableToBody.Add(vtb);
                    dbContext.SaveChanges();
                    id = vtb.VariableToBodyId;
                    for (int i = 0; i < VariableName.Count; i++)
                    {
                        VariableToBodyDetail vtbd = new VariableToBodyDetail();
                        string vaf = VariableField[i];
                        string van = VariableName[i];
                        vtbd.VariableToBodyId = vtb.VariableToBodyId;
                        vtbd.VariableName = van;
                        vtbd.VariableField = vaf;
                        dbContext.VariableToBodyDetail.Add(vtbd);
                    }
                    dbContext.SaveChanges();

                    status = 200; message = "Success Add Data";
                }
                catch(Exception ex)
{
                    message = ex.Message;
                    status = 400;

                    var mu = dbContext.VariableToBody.Where(m => m.VariableToBodyId == id).FirstOrDefault();
                    dbContext.VariableToBody.Remove(mu);

                    var mud = dbContext.VariableToBodyDetail.Where(m => m.VariableToBodyId == id).ToList();
                    foreach (var val in mud)
                    {
                        dbContext.VariableToBodyDetail.Remove(val);
                    }
                    dbContext.SaveChanges();
                }
            }
            else
            {
                try
                {
                    var vtb = dbContext.VariableToBody.Find(id);
                    vtb.VariableToBodyName = nama;                    
                    dbContext.SaveChanges();

                    var vtbdt = dbContext.VariableToBodyDetail.Where(m => m.VariableToBodyId == id).ToList();
                    foreach (var val in vtbdt)
                    {
                        dbContext.VariableToBodyDetail.Remove(val);
                    }
                    dbContext.SaveChanges();

                    for (int i = 0; i < VariableName.Count; i++)
                    {
                        VariableToBodyDetail vtbd = new VariableToBodyDetail();
                        string vaf = VariableField[i];
                        string van = VariableName[i];
                        vtbd.VariableToBodyId = vtb.VariableToBodyId;
                        vtbd.VariableName = van;
                        vtbd.VariableField = vaf;
                        dbContext.VariableToBodyDetail.Add(vtbd);
                    }
                    dbContext.SaveChanges();

                    status = 200; message = "Success Change Data";
                }
                catch (Exception ex)
                {
                    message = ex.Message;
                    status = 400;
                }
            }

            return Json(new { status = status, message = message });
        }

        public JsonResult DeleteVar(int id)
        {
            int status = 200; string message = "Success";
            try
            {
                var VB = dbContext.VariableToBody.Where(m => m.VariableToBodyId == id).FirstOrDefault();
                dbContext.VariableToBody.Remove(VB);

                var VBD = dbContext.VariableToBodyDetail.Where(m => m.VariableToBodyId == id).ToList();
                foreach (var val in VBD)
                {
                    dbContext.VariableToBodyDetail.Remove(val);
                }
                dbContext.SaveChanges();
            }
            catch (Exception e)
            {
                status = 400;
                message = e.Message;
            }
            return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ListBodyMsg()
        {
            ViewBag.DataList = dbContext.Body_Message;

            return View();
        }

        public ActionResult FormBodyMsg(int id =0)
        {
            ViewBag.Body_Message = dbContext.Body_Message.Find(id);
            ViewBag.VariableBody = dbContext.VariableToBody;
            ViewBag.Id = id;
            return View();
        }

        [HttpPost]
        public JsonResult SaveBodyMsg()
        {
            string message = ""; int status = 200;
            long Body_MessageId = Int64.Parse(Request["Body_MessageId"]);
            string Nama_Body = Request["Nama_Body"];
            int VariableToBodyId = int.Parse(Request["VariableToBodyId"]);
            String Body = Request["Body"];
            if (Body_MessageId == 0)
            {
                try
                {
                    Body_Message bm = new Body_Message();
                    bm.Nama_Body = Nama_Body;
                    bm.VariableToBodyId = VariableToBodyId;
                    bm.Body = Body;
                    dbContext.Body_Message.Add(bm);
                    dbContext.SaveChanges();

                    status = 200; message = "Success Add Data";
                }
                catch (Exception ex)
                {
                    message = ex.Message;
                    status = 400;
                }
            }
            else
            {
                try
                {
                    var bmu = dbContext.Body_Message.Find(Body_MessageId);
                    bmu.Body = Body;
                    bmu.Nama_Body = Nama_Body;
                    bmu.VariableToBodyId = VariableToBodyId;
                    dbContext.SaveChanges();

                    status = 200; message = "Success Change Data";
                }
                catch (Exception ex)
                {
                    message = ex.Message;
                    status = 400;
                }
            }

            return Json(new { status = status, message = message });
        }

        [HttpGet]
        public JsonResult DeleteBody(int id)
        {
            int status = 200; string message = "Success";
            var cek = dbContext.Project.Where(m => m.Body_MessageId == id).FirstOrDefault();
            if(cek == null)
            {
                try
                {
                    var VB = dbContext.Body_Message.Where(m => m.Body_MessageId == id).FirstOrDefault();
                    dbContext.Body_Message.Remove(VB);

                    dbContext.SaveChanges();
                }
                catch (Exception e)
                {
                    status = 400;
                    message = e.Message;
                }
            }
            else
            {
                status = 400;
                message = "Tidak bisa delete, karena body message masih digunakan dibeberapa project";
            }

            return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult getVardetail(int id)
        {
            var data = dbContext.VariableToBodyDetail.Where(m => m.VariableToBodyId == id).ToList();
            return Json(new { data = data}, JsonRequestBehavior.AllowGet);
        }
    }
}

gtv_tele/Views/Setting/FormBodyMsg.cshtml
@{
    ViewBag.Title = "FormBodyMsg";
    Layout = "~/Views/Shared/_TemaAdminLTE.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Settings
            <small>Form Variable Field</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-gear"></i> Setting</a></li>
            <li class="active"><a href="#">Form Variable Field</a></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="col-md-12">
            <div class="row">
                <!-- Horizontal Form -->
                <div class="box box-info">
                    <div class="box-header with-border">

                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">

                        <!-- form start -->
                        @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal", id = "form-bodymsg", name = "form-bodymsg" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="box-body">
                                <input type="hidden" id="Body_MessageId" name="Body_MessageId" value="@ViewBag.Id" />
                                <div class="form-group">
                                    <label class="col-md-2 col-form-label text-md-right">Variable Body</label>
                                    <div class="col-sm-3">
                                        <select class="form-control select2" id="VariableToBodyId" name="VariableToBodyId" onchange="SetVar()">
                                            <option value="0">Select</option>
                                            @foreach (var varbody in ViewBag.VariableBody)
                                            {
                                                <option value="@varbody.VariableToBodyId"
                                                        @if (ViewBag.Body_Message != null) { if (varbody.VariableToBodyId == ViewBag.Body_Message.VariableToBodyId) { <text> selected</text>  }  }>
                                                    @varbody.VariableToBodyName
                                                </option>
                                            }
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="name" class="col-md-2 col-form-label text-md-right">Detail Variable</label>

                                    <div class="col-md-6">
                                        <div class="callout callout">
                                            <table class="table">
                                                <thead>
                                                    <tr>
                                                        <th>Variable Name</th>
                                                        <th>Field Name</th>
                                                    </tr>
                                                </thead>
                                                <tbody id="keterangan">
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-2 col-form-label text-md-right">Nama Body</label>
                                    <div class="col-sm-2">
                                        <input type="text" class="form-control" id="Nama_Body" name="Nama_Body" value="@if (ViewBag.Body_Message != null) { @ViewBag.Body_Message.Nama_Body }" placeholder="Nama Body" autocomplete="off">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-2 col-form-label text-md-right">Body Message</label>
                                    <div class="col-sm-6">
                                        <textarea type="text" class="form-control" id="Body" cols="5" rows="5" name="Body" placeholder="Body Message" autocomplete="off">@if (ViewBag.Body_Message != null) { @ViewBag.Body_Message.Body }</textarea>
                                    </div>
                                </div>
                            </div><!-- /.box-body -->
                            <div class="box-footer">
                                <button type="submit" class="btn btn-success" value="submit" id="submit" name="submit"><span class="fa fa-send"></span> Submit</button>
                            </div><!-- /.box-footer -->

                        }

                    </div>

                    <!-- Loading (remove the following to stop the loading)-->
                    <div class="overlay" id="loading" style="display:none;">
                        <i class="fa fa-refresh fa-spin"></i>
                    </div>
                    <!-- end loading -->

                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>

@section js{
    <script>

        SetVar();
        function SetVar() {
            var id = $('#VariableToBodyId').val();
            $.ajax({
                url: "@Url.Action("getVardetail","Setting")",
                type: "GET",
                data: {
                    id: id
                },
                success: function(data) {
                    var tmp = "";
                    $.each(data.data, function(index, value) {
                        tmp += "<tr>";
                        tmp += "<td>" + value['VariableName'] + "</td>";
                        tmp += "<td>" + value['VariableField'] + "</td>";
                        tmp += "</tr>";
                    });
                    $('#keterangan').replaceWith($('#keterangan').html(tmp));
                }
            });
        }

        $(function () {
            $('.select2').select2();

            $('#form-bodymsg').submit(function (e) {
                e.preventDefault();
                var url = "@Url.Action("SaveBodyMsg", "Setting")";
                var formData = new FormData($('#form-bodymsg')[0]);
                //showLoad();

                Swal.fire({
                    title: 'Form Body Message',
                    text: 'Yakin Mau Lanjut ?',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Ya, Lanjut !',
                    showLoaderOnConfirm: true,
                    preConfirm: (login) => {
                        $.ajax({
                            url: url,
                            type: 'POST',
                            data: formData,
                            contentType: false,
                            processData: false,
                            beforeSend: function () {
                                $('#loading').css('display', 'block');
                            },
                            success: function (response) {
                                //alert(JSON.stringify(response));
                                //hideLoad();
                                if (response.status == 200) {
                                    $('#loading').css('display', 'none');
                                    Swal.fire({
                                        icon: 'success',
                                        title: response.message,
                                        onClose: () => {
                                            $('#form-bodymsg')[0].reset();
                                        }
                                    });
                                } else {
                                    if (response.status == 400) {
                                        $('#loading').css('display', 'none');
                                        Swal.fire({
                                            icon: 'error',
                                            title: response.message,
                                            onClose: () => {
                                                $('#form-bodymsg')[0].reset();
                                            }
                                        });
                                    }
                                }
                            },
                            error: function (response) {
                                //hideLoad();
                                $('#loading').css('display', 'none');
                                Swal.fire({
                                    icon: 'error',
                                    title: 'Error',
                                    onClose: () => {
                                        $('#form-bodymsg')[0].reset();
                                    }
                                });
                            }
                        });
                    }
                });
            });
        });
    </script>
}

gtv_tele/Views/Setting/FormVarToField.cshtml
@{
    ViewBag.Title = "FormVarToField";
    Layout = "~/Views/Shared/_TemaAdminLTE.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Settings
            <small>Form Variable Field</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-gear"></i> Setting</a></li>
            <li class="active"><a href="#">Form Variable Field</a></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="col-md-12">
            <div class="row">
                <!-- Horizontal Form -->
                <div class="box box-info">
                    <div class="box-header with-border">

                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">

                        <!-- form start -->
                        @using (Html.BeginForm(null, null, FormMethod.Get, new { @class = "form-horizontal", id = "form-variable", name = "form-variable" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <input type="hidden" id="id" name="id" value="@ViewBag.Id" />
                            <div class="box-body">
                                <div class="form-group">
                                    <div class="col-sm-2">
                                        <label>Nama</label>
                                        <div class="input-group date">
                                            <input type="text" class="form-control" id="VariableToBodyName" name="VariableToBodyName" value="@if (ViewBag.VariableToBodyName != null) { @ViewBag.VariableToBodyName.VariableToBodyName }" placeholder="VariableToBodyName" autocomplete="off">
                                        </div>
                                    </div>
                                </div>
                            </div><!-- /.box-body --><div class="box-footer">
                                <div>
                                    <button type="submit" class="btn btn-success" value="submit" id="submit" name="submit"><span class="fa fa-send"></span> Submit</button>
                                </div>
                            </div><!-- /.box-footer -->

                            <div class="card-body table-responsive p-0">
                                <table id="tb_list" class="table table-bordered table-responsive">
                                    <thead>
                                        <tr>
                                            <th>Varibale Name</th>
                                            <th>Varibale Field Name</th>
                                            <th style="width: 15%; text-align: center">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody id="tbod">

                                        @foreach (dynamic val in ViewBag.DataList)
                                        {
                                            <tr>
                                                <td><input type="text" class="form-control" id="VariableName[]" name="VariableName[]" value="@val.VariableName" /></td>
                                                <td>
                                                    <select class="form-control" id="VariableField[]" name="VariableField[]">
                                                        @foreach (var f in ViewBag.FieldName)
                                                        {
                                                            string select = "selected";
                                                            <option value="@f"
                                                                    @if (val.VariableField == f) { @select } }>
                                                                @f
                                                            </option>
                                                        }
                                                    </select>
                                                </td>

                                                <td>
                                                    <a href="#" id="delete" class="btn btn-danger delete">Delete</a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td colspan="3"><a class="btn btn-success pull-right" id="add" name="add"><span class="fa fa-plus"></span></a></td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        }

                    </div>

                    <!-- Loading (remove the following to stop the loading)-->
                    <div class="overlay" id="loading" style="display:none;">
                        <i class="fa fa-refresh fa-spin"></i>
                    </div>
                    <!-- end loading -->

                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>

@section js{
    <script>

        $("#add").on("click", function() {
            var html = '<tr>' +
                '<td><input type="text" class="form-control" id="VariableName[]" name="VariableName[]" /></td>' +
                '<td><select class="form-control" id="VariableField[]" name="VariableField[]">' +
                            @foreach(var ok in ViewBag.FieldName)
            {
                <text>
                   '<option value="@ok">@ok</option>'+
                </text>
            }
                '</select> </td>' +
                '<td> <a href="#" id="delete"  class="btn btn-danger delete">Delete</a> </td>';
            $("#tbod").append(html);
            selectDro();
        });



        function deleteRow() {
            var par = $(this).parent().parent();
            par.remove();
        };

        $("#tb_list").on("click", ".delete", deleteRow);

        $(function () {
            $('#form-variable').submit(function (e) {
                e.preventDefault();
                var url = "@Url.Action("SaveData", "Setting")";
                var formData = new FormData($('#form-variable')[0]);
                //showLoad();

                Swal.fire({
                    title: 'Form Variable',
                    text: 'Yakin Mau Lanjut ?',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Ya, Lanjut !',
                    showLoaderOnConfirm: true,
                    preConfirm: (login) => {
                        $.ajax({
                            url: url,
                            type: 'POST',
                            data: formData,
                            contentType: false,
                            processData: false,
                            beforeSend: function () {
                                $('#loading').css('display', 'block');
                            },
                            success: function (response) {
                                //alert(JSON.stringify(response));
                                //hideLoad();
                                if (response.status == 200) {
                                    $('#loading').css('display', 'none');
                                    Swal.fire({
                                        icon: 'success',
                                        title: response.message,
                                        onClose: () => {
                                            $('#form-variable')[0].reset();
                                        }
                                    });
                                } else {
                                    if (response.status == 400) {
                                        $('#loading').css('display', 'none');
                                        Swal.fire({
                                            icon: 'error',
                                            title: response.message,
                                            onClose: () => {
                                                $('#form-variable')[0].reset();
                                            }
                                        });
                                    }
                                }
                            },
                            error: function (response) {
                                //hideLoad();
                                $('#loading').css('display', 'none');
                                Swal.fire({
                                    icon: 'error',
                                    title: 'Error',
                                    onClose: () => {
                                        $('#form-variable')[0].reset();
                                    }
                                });
                            }
                        });
                    }
                });
            });
        });
    </script>
}