gtv_tele/Controllers/ListUpload/ListUploadController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;
using System.Web.UI.WebControls.WebParts;
using gtv_tele.DataAccess;
namespace gtv_tele.Controllers.ListUpload
{
    [Authorize]
    public class ListUploadController : Controller
    {
        AuthenticationDB dbContext = new AuthenticationDB();
        // GET: ListUpload
        public ActionResult Index()
        {
            var datax = (from MU in dbContext.Master_Upload
                         join PJ in dbContext.Project on MU.ProjectId equals PJ.ProjectId
                         join CU in dbContext.Customer on PJ.CustomerId equals CU.CustomerId
                         join US in dbContext.Users on MU.UserId equals US.UserId
                         select new
                         {
                             CustomerName = CU.CustomerName,
                             ProjectName = PJ.ProjectName,
                             Cycle = MU.Cycle,
                             Master_UploadId = MU.Master_UploadId,
                             Part = MU.Part,
                             FileName = MU.FileName,
                             FilePath = MU.FilePath,
                             UserId = MU.UserId,
                             UserName = (US.FirstName + " " + US.LastName).Trim(),
                             Created_at = MU.Created_at,
                             Updated_at = MU.Updated_at,
                         });
            ViewBag.ListUpload = datax;
            return View();
        }

        public ActionResult Detail(int id=0)
        {
            Master_Upload master = dbContext.Master_Upload.Where(m => m.Master_UploadId == id).FirstOrDefault();
            List<Master_Upload_Detail> data = dbContext.Master_Upload_Detail.Where(m => m.Master_UploadId == id).ToList();
            ViewBag.DataDetail = data;
            ViewBag.DataMaster = master;
            return View();
        }

        public JsonResult Delete(int id =0)
        {
            int status = 200; string message = "Success";
            try
            {
                var mu = dbContext.Master_Upload.Where(m => m.Master_UploadId == id).FirstOrDefault();
                dbContext.Master_Upload.Remove(mu);                

                var mud = dbContext.Master_Upload_Detail.Where(m => m.Master_UploadId == id).ToList();
                foreach(var val in mud)
                {
                    dbContext.Master_Upload_Detail.Remove(val);                    
                    var hr = dbContext.History_Read.Where(mhr => mhr.Master_Upload_DetailId == val.Master_Upload_DetailId).ToList();
                    foreach (var vhar in hr)
                    {
                        dbContext.History_Read.Remove(vhar);                        
                    }
                    var vc = dbContext.Verify_Code.Where(mvc => mvc.Master_Upload_DetailId == val.Master_Upload_DetailId).ToList();
                    foreach (var vvc in vc)
                    {
                        dbContext.Verify_Code.Remove(vvc);                        
                    }
                }
                dbContext.SaveChanges();
            }catch(Exception e)
            {
                status = 400;
                message = e.Message;
            }
            return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
        }
    }
}

gtv_tele/Views/ListUpload/Detail.cshtml
@{
    Layout = null;
    var MasterData = ViewBag.DataMaster;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">@MasterData.Cycle - @MasterData.Part</h4>
</div>
<div class="modal-body">
    <div class="box-body">
        <div class="card-body table-responsive p-0">
            <table id="tb_list" class="table table-bordered table-responsive">
                <thead>
                    <tr>
                        <th>Nopol</th>
                        <th>Nama</th>
                        <th>NoHP</th>
                        <th>Status</th>
                        <th>Message Status</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var val in ViewBag.DataDetail)
                    {
                        <tr>
                            <td>@val.Account</td>
                            <td>@val.Nama</td>
                            <td>@val.NoHP</td>
                            <td>@val.Status</td>
                            <td>@val.Message_Status</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default pull-right" data-dismiss="modal">Close</button>
</div>

gtv_tele/Views/ListUpload/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_TemaAdminLTE.cshtml";
}

<div class="content-wrapper">
    <section class="content-header">
        <h1>
            List Upload
        </h1>
        <ol class="breadcrumb">
            <li class="active"><a href="#"><i class="fa fa-list"></i> List Upload</a></li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="center-block">
                <div class="col-lg-12">
                    <div class="box box-info">
                        <div class="box-header with-border">
                            <h3 class="box-title">List Upload</h3>
                        </div>
                        <div class="box-body">
                            <div class="card-body table-responsive p-0">
                                <table id="tb_list" class="table table-bordered table-responsive">
                                    <thead>
                                        <tr>
                                            <th>Customer</th>
                                            <th>Project</th>
                                            <th>Cycle/Part</th>
                                            <th>Upload By</th>
                                            <th>Created at</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (dynamic val in ViewBag.ListUpload)
                                        {
                                            var id = val.GetType().GetProperty("Master_UploadId").GetValue(val);
                                            //var crete = new DateTime(val.GetType().GetProperty("Created_at").GetValue(val));
                                            <tr>
                                                <td>@val.GetType().GetProperty("CustomerName").GetValue(val)</td>
                                                <td>@val.GetType().GetProperty("ProjectName").GetValue(val)</td>
                                                <td>@val.GetType().GetProperty("Cycle").GetValue(val)/@val.GetType().GetProperty("Part").GetValue(val)</td>
                                                <td>@val.GetType().GetProperty("UserName").GetValue(val)</td>
                                                <td>@val.GetType().GetProperty("Created_at").GetValue(val)</td>
                                                <td>
                                                    <a href="@Url.Action("Detail","ListUpload", new { id=id})" data-toggle="modal" data-target="#modal-default-@id" class="btn btn-info">Detail</a>
                                                    <a href="#" onclick="DeleteMU('@id')" class="btn btn-danger">Delete</a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

@foreach (dynamic val in ViewBag.ListUpload)
{
    var id = val.GetType().GetProperty("Master_UploadId").GetValue(val);
    <div class="modal fade" id="modal-default-@id">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">

            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
}


@section js{
    <script>
        $("#tb_list").DataTable({
            "processing": true
        });

        function DeleteMU(id) {

            Swal.fire({
                title: 'Delete',
                text: 'Yakin Mau Delete ?',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya, Lanjut !',
                showLoaderOnConfirm: true,
                preConfirm: (ok) => {
                    $.getJSON("@Url.Action("Delete","ListUpload")", { id: id }, function (respon) {
                        if (respon.status == 200) {
                            Swal.fire({
                                title: "Success",
                                text: respon.message,
                                icon: "success",
                                onClose: () => {
                                    window.location.reload();
                                }
                            });
                        } else {
                            Swal.fire({
                                title: "Failed",
                                text: respon.message,
                                icon: "error",
                                onClose: () => {
                                    window.location.reload();
                                }
                            });
                        }
                    });
                }
            });
        }
    </script>
}